replicaCount: 1

image:
  tag: "latest"

frontend:
  image:
    repository: nginx
  service:
    port: 80
  replicaCount: 2

backend:
  image:
    repository: "ekaterina737/my-flask-backend"
  service:
    port: 5000
  replicaCount: 1

  livenessProbe:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /ready
      port: 5000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3

ingress:
  enabled: true
  host: ""
  className: nginx
  annotations: {}
